### ISSUE TITLE
Roost block rendering issue causes crash

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/Chickens#6]
A user playing the modpack "FTB One" got a crash which appears to be due to the "roost" block.

Versions:
Minecraft `1.19`
Forge `41.0.45`
Chickens mod `chickensmod-1.19-1.0.7.jar`
Modpack `FTB One 1.2.1`

Crash:
https://paste.feed-the-beast.com/view/a9bcdaaf
```
Description: Rendering Block Entity
 
java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "p_135833_" is null
        at net.minecraft.resources.ResourceLocation.m_135832_(ResourceLocation.java:73)
        at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42)
        at net.minecraft.resources.ResourceLocation.m_135820_(ResourceLocation.java:56)
        at net.creeperhost.chickens.client.render.RenderRoost.render(RenderRoost.java:32)
        at net.creeperhost.chickens.client.render.RenderRoost.m_6922_(RenderRoost.java:20)
        at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:90)
        at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112297_(BlockEntityRenderDispatcher.java:79)
```

Removing the Roost block using NBTExplorer allows one to join the world properly again.

This was the data of the problematic roost block which had to be removed since it caused an error:
![image](https://user-images.githubusercontent.com/17010632/176985023-5ba6f60e-5d82-4679-93d7-1560eb65757a.png)

This is a healthy roost block not causing any errors, for comparison:
![image](https://user-images.githubusercontent.com/17010632/176985034-388cd326-8865-4e49-ba1d-98c678a736e0.png)

Thanks in advance for investigating!

**Comment by gigabit101** [comment]
Fixed in latest release
